SELECT * FROM STADIUM;

UPDATE STADIUM SET STADIUM_NAME = '섹섹보' WHERE STADIUM_ID = 'F05';

ALTER TABLE PLAYER ADD (ROW_ID NUMBER);

SELECT * FROM PLAYER;

UPDATE PLAYER SET ROW_ID = ROWNUM ; 


SELECT INSTR('ENERGYEXPERT','X') FROM DUAL;

SELECT INSTR('ENERGY EXPERT','E',4) FROM DUAL; 

SELECT PLAYER_NAME,SUBSTR(PLAYER_NAME,1,LENGTH(PLAYER_NAME)-1)||'*' FROM PLAYER;


SELECT ADDRESS,REGEXP_REPLACE(ADDRESS,'[0-9]','X') FROM STADIUM WHERE REGEXP_LIKE(ADDRESS,'서울|인천');

-- PLAYER 테이블에서 PLAYER_ID를 활용하여 전체 선수를 4개의 그룹(0~3)에 배정해라.
SELECT PLAYER_ID,MOD(PLAYER_ID,4) AS "새로운 그룹" FROM PLAYER;

SELECT TO_CHAR (SYSDATE,'yyyy/mm/dd/HH24.MI/SS') FROM DUAL;

SELECT  EXTRACT(YEAR FROM TO_DATE('2022/11/11','YYYY.MM.DD'))FROM DUAL;

SELECT TO_DATE('2022/11/11') FROM DUAL;


SELECT PLAYER_NAME,BIRTH_DATE,TRUNC(SYSDATE-BIRTH_DATE,0) FROM PLAYER;

DESC PLAYER;

SELECT PLAYER_NAME,POSITION,NVL(POSITION,'없음') AS "포지션" FROM PLAYER;

SELECT PLAYER_NAME,POSITION,
CASE WHEN POSITION IS NULL THEN '없음' ELSE POSITION END AS "포지션" FROM PLAYER;


SELECT * FROM EMP;

SELECT ENAME,SAL,COMM,(SAL*12)+NVL(COMM,0) AS "연봉" FROM EMP;

SELECT ENAME,SAL,COMM,(SAL*12)+
CASE WHEN COMM IS NULL THEN 0 ELSE COMM END
 AS "연봉" FROM EMP;